LISTING_TEMPLATES = [
    { "price": "$4,585", "title": "Luxury Studio in Historic District", "img": "listing_1/cover.jpg" },
    { "price": "$4,689", "title": "Modern Cabin with View", "img": "listing_2/cover.jpg" },
    { "price": "$3,709", "title": "Sunny Studio near Park", "img": "listing_3/cover.jpg" },
    { "price": "$3,976", "title": "Affordable Condo by the Lake", "img": "listing_4/cover.jpg" },
    { "price": "$4,236", "title": "Urban Studio in Suburbs", "img": "listing_5/cover.jpg" },
    { "price": "$1,088", "title": "Spacious Cabin by the Lake", "img": "listing_6/cover.jpg" },
    { "price": "$3,201", "title": "Cozy Studio uptown", "img": "listing_7/cover.jpg" },
    { "price": "$3,551", "title": "Charming Bungalow Downtown", "img": "listing_8/cover.jpg" },
    { "price": "$1,741", "title": "Charming Loft by the Lake", "img": "listing_9/cover.jpg" },
    { "price": "$3,120", "title": "Luxury Suite near Metro", "img": "listing_10/cover.jpg" },
    { "price": "$1,175", "title": "Affordable Bungalow Downtown", "img": "listing_11/cover.jpg" },
    { "price": "$1,785", "title": "Modern Loft near Park", "img": "listing_12/cover.jpg" },
    { "price": "$3,994", "title": "Luxury Cabin in Historic District", "img": "listing_13/cover.jpg" },
    { "price": "$1,885", "title": "Luxury Suite near Park", "img": "listing_14/cover.jpg" },
    { "price": "$3,727", "title": "Charming Cabin in Historic District", "img": "listing_15/cover.jpg" },
    { "price": "$4,126", "title": "Spacious Penthouse with View", "img": "listing_16/cover.jpg" },
    { "price": "$3,879", "title": "Private Apartment in Suburbs", "img": "listing_17/cover.jpg" },
    { "price": "$4,511", "title": "Cozy Bungalow with View", "img": "listing_18/cover.jpg" },
    { "price": "$2,165", "title": "Modern Villa Downtown", "img": "listing_19/cover.jpg" },
    { "price": "$1,054", "title": "Spacious Bungalow near Metro", "img": "listing_20/cover.jpg" },
    { "price": "$4,314", "title": "Cozy Cabin Downtown", "img": "listing_21/cover.jpg" },
    { "price": "$3,948", "title": "Urban Villa by the Lake", "img": "listing_22/cover.jpg" },
    { "price": "$3,034", "title": "Sunny Condo Downtown", "img": "listing_23/cover.jpg" },
    { "price": "$811", "title": "Private Studio in Historic District", "img": "listing_24/cover.jpg" },
    { "price": "$965", "title": "Urban Suite near Park", "img": "listing_25/cover.jpg" },
    { "price": "$831", "title": "Secluded Penthouse uptown", "img": "listing_26/cover.jpg" },
    { "price": "$1,099", "title": "Modern Studio Downtown", "img": "listing_27/cover.jpg" },
    { "price": "$3,763", "title": "Spacious Bungalow Downtown", "img": "listing_28/cover.jpg" },
    { "price": "$3,085", "title": "Private Studio near Metro", "img": "listing_29/cover.jpg" },
    { "price": "$3,162", "title": "Cozy Villa in Suburbs", "img": "listing_30/cover.jpg" },
    { "price": "$2,954", "title": "Modern Studio Downtown", "img": "listing_31/cover.jpg" },
    { "price": "$1,706", "title": "Spacious Condo by the Lake", "img": "listing_32/cover.jpg" },
    { "price": "$2,354", "title": "Private Villa in Suburbs", "img": "listing_33/cover.jpg" },
    { "price": "$1,977", "title": "Urban Penthouse in Historic District", "img": "listing_34/cover.jpg" },
    { "price": "$3,960", "title": "Luxury Loft uptown", "img": "listing_35/cover.jpg" },
    { "price": "$2,779", "title": "Modern Penthouse in Suburbs", "img": "listing_36/cover.jpg" },
    { "price": "$1,559", "title": "Spacious Suite with View", "img": "listing_37/cover.jpg" },
    { "price": "$828", "title": "Affordable Condo by the Lake", "img": "listing_38/cover.jpg" },
    { "price": "$3,992", "title": "Spacious Bungalow near Park", "img": "listing_39/cover.jpg" },
    { "price": "$3,098", "title": "Charming Penthouse uptown", "img": "listing_40/cover.jpg" },
    { "price": "$2,894", "title": "Affordable Loft in Historic District", "img": "listing_41/cover.jpg" },
    { "price": "$1,710", "title": "Private Studio with View", "img": "listing_42/cover.jpg" },
    { "price": "$4,374", "title": "Charming Bungalow near Park", "img": "listing_43/cover.jpg" },
    { "price": "$1,154", "title": "Private Room in Historic District", "img": "listing_44/cover.jpg" },
    { "price": "$3,203", "title": "Luxury Suite Downtown", "img": "listing_45/cover.jpg" },
    { "price": "$1,787", "title": "Cozy Bungalow in Historic District", "img": "listing_46/cover.jpg" },
    { "price": "$2,618", "title": "Cozy Villa in Historic District", "img": "listing_47/cover.jpg" },
    { "price": "$2,670", "title": "Secluded Suite near Park", "img": "listing_48/cover.jpg" },
    { "price": "$1,896", "title": "Modern Penthouse near Metro", "img": "listing_49/cover.jpg" },
    { "price": "$3,861", "title": "Private Villa by the Lake", "img": "listing_50/cover.jpg" },
    { "price": "$4,938", "title": "Secluded Bungalow uptown", "img": "listing_51/cover.jpg" },
    { "price": "$1,251", "title": "Urban Bungalow in Historic District", "img": "listing_52/cover.jpg" },
    { "price": "$1,298", "title": "Spacious Apartment with View", "img": "listing_53/cover.jpg" },
    { "price": "$3,617", "title": "Luxury Room uptown", "img": "listing_54/cover.jpg" },
    { "price": "$2,606", "title": "Affordable Cabin near Park", "img": "listing_55/cover.jpg" },
    { "price": "$1,680", "title": "Urban Cabin in Historic District", "img": "listing_56/cover.jpg" },
    { "price": "$1,213", "title": "Spacious Condo by the Lake", "img": "listing_57/cover.jpg" },
    { "price": "$4,525", "title": "Secluded Studio Downtown", "img": "listing_58/cover.jpg" },
    { "price": "$3,510", "title": "Charming Room in Suburbs", "img": "listing_59/cover.jpg" },
    { "price": "$923", "title": "Charming Loft with View", "img": "listing_60/cover.jpg" },
    { "price": "$4,370", "title": "Luxury Loft in Suburbs", "img": "listing_61/cover.jpg" },
    { "price": "$2,881", "title": "Private Suite near Park", "img": "listing_62/cover.jpg" },
    { "price": "$1,610", "title": "Affordable Room near Park", "img": "listing_63/cover.jpg" },
    { "price": "$2,508", "title": "Sunny Villa in Historic District", "img": "listing_64/cover.jpg" },
    { "price": "$3,165", "title": "Charming Suite near Park", "img": "listing_65/cover.jpg" },
    { "price": "$4,687", "title": "Secluded Loft in Suburbs", "img": "listing_66/cover.jpg" },
    { "price": "$4,569", "title": "Modern Studio uptown", "img": "listing_67/cover.jpg" },
    { "price": "$3,626", "title": "Secluded Bungalow in Suburbs", "img": "listing_68/cover.jpg" },
    { "price": "$4,462", "title": "Modern Suite near Metro", "img": "listing_69/cover.jpg" },
    { "price": "$1,219", "title": "Cozy Cabin with View", "img": "listing_70/cover.jpg" },
    { "price": "$4,887", "title": "Urban Apartment near Park", "img": "listing_71/cover.jpg" },
    { "price": "$3,200", "title": "Luxury Studio near Park", "img": "listing_72/cover.jpg" },
    { "price": "$4,574", "title": "Spacious Cabin in Suburbs", "img": "listing_73/cover.jpg" },
    { "price": "$4,368", "title": "Cozy Loft in Historic District", "img": "listing_74/cover.jpg" },
    { "price": "$3,774", "title": "Charming Cabin uptown", "img": "listing_75/cover.jpg" },
    { "price": "$2,416", "title": "Cozy Condo by the Lake", "img": "listing_76/cover.jpg" },
    { "price": "$3,175", "title": "Private Condo with View", "img": "listing_77/cover.jpg" },
    { "price": "$2,641", "title": "Sunny Cabin near Park", "img": "listing_78/cover.jpg" },
    { "price": "$3,172", "title": "Secluded Cabin Downtown", "img": "listing_79/cover.jpg" },
    { "price": "$2,424", "title": "Spacious Villa by the Lake", "img": "listing_80/cover.jpg" },
    { "price": "$2,588", "title": "Sunny Apartment near Metro", "img": "listing_81/cover.jpg" },
    { "price": "$4,709", "title": "Sunny Loft in Historic District", "img": "listing_82/cover.jpg" },
    { "price": "$3,089", "title": "Luxury Suite near Park", "img": "listing_83/cover.jpg" },
    { "price": "$3,843", "title": "Private Cabin in Suburbs", "img": "listing_84/cover.jpg" },
    { "price": "$1,717", "title": "Modern Apartment Downtown", "img": "listing_85/cover.jpg" },
    { "price": "$1,419", "title": "Cozy Apartment by the Lake", "img": "listing_86/cover.jpg" },
    { "price": "$990", "title": "Spacious Condo in Suburbs", "img": "listing_87/cover.jpg" },
    { "price": "$4,525", "title": "Spacious Cabin near Park", "img": "listing_88/cover.jpg" },
    { "price": "$4,723", "title": "Secluded Penthouse near Metro", "img": "listing_89/cover.jpg" },
    { "price": "$4,278", "title": "Luxury Apartment in Suburbs", "img": "listing_90/cover.jpg" },
    { "price": "$3,377", "title": "Affordable Penthouse near Park", "img": "listing_91/cover.jpg" },
    { "price": "$3,805", "title": "Charming Condo Downtown", "img": "listing_92/cover.jpg" },
    { "price": "$2,525", "title": "Urban Bungalow uptown", "img": "listing_93/cover.jpg" },
    { "price": "$2,159", "title": "Affordable Studio uptown", "img": "listing_94/cover.jpg" },
    { "price": "$1,044", "title": "Sunny Room near Metro", "img": "listing_95/cover.jpg" },
    { "price": "$1,137", "title": "Private Cabin with View", "img": "listing_96/cover.jpg" },
    { "price": "$4,745", "title": "Luxury Studio Downtown", "img": "listing_97/cover.jpg" },
    { "price": "$2,346", "title": "Charming Suite near Metro", "img": "listing_98/cover.jpg" },
    { "price": "$3,373", "title": "Luxury Studio by the Lake", "img": "listing_99/cover.jpg" },
    { "price": "$3,577", "title": "Cozy Condo near Metro", "img": "listing_100/cover.jpg" },
]